title: Foushan Abdul Khader
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Foushan, a trained Business Intelligence Analyst embeded with 10-years of experience in various industries and with an electrical and electronics engineering university education. I am passionate about diving in data, and building business logics when communicating  business and tech teams.
  My experience in handling and analysing performance responses using data lead me to this exciting path with analytical industry. Go through my profile, which reflects the paths and decisions I have made to pursue this exciitng career. 
  <br><br>
  <a href="https://www.linkedin.com/in/foushan-abdul-khader">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/foushan.abdul.khader">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.https://www.notion.so/foushanabdulkhader">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
